# DSA8021 Machine Learning Coursework 2026

Assessment will be based on conceptual equivalencies and academic judgement. The study regulations are found here -> https://www.qub.ac.uk/directorates/media/Media,837249,smxx.pdf

# Part 1: Theory of Neural Networks (total of 25 marks)

## Neural Network Basics (5 Marks)

Consider the network architecture shown below, along with weights(note that weights $w_{5}$ and $w_{6}$ are biases). This network is used for a classification problem, and all of the activation functions are sigmoids:
$$ f(m) = \frac{1}{1 + e^{-m}} $$

![NN architecture](Coursework_Network.png "Neural Network")

When the input $x_{1} = 1$, $x_{2} = 1$ is given to the network, the target output is $z = 1$.

- A) Calculate the output of the network for the given input.
- B) With justification, choose an error function for the network and evaluate this error function given the target value and the output you have calculated.
- C) To improve the error, should weight $w_{7}$ be increased or decreased? Note that you do not need to perform an explicit calculation.
- D) Describe two changes you could make to the network architecture that you would expect to improve its performance. Which of these would you expect to lead to the most improvement?

## Deep Learning (20 Marks, 10 per question)
Choose **two** of the following questions to answer. In each case, your answer should be **no more than 250 words**, and should include a figure:
- A) Explain what is meant by _overfitting_ in the context of training neural networks, and describe two methods for avoiding overfitting.
- B) Describe a method by which invariances in the training data can be taken into account when training a regression problem? How does your answer differ for a classification problem?
- C) Explain the function of _convolutional layers_ and _pooling layers_ in a convolutional neural network.
- D) Draw a schematic figure of a generative adversarial network (GAN): why are two networks needed in a GAN, and why do they compete with each other?

# Part 2: Practical Scenario (75 Marks)
## Build an image classifier

In this scenario you have started work for a company that wants you to develop a machine learning tool for determining how many dots are on the visible surface of a dice. Your work will be assessed by two people with different motivations:
-  The client, who is mainly interested in the  accuracy of your model at classiying the dice images
-  Your supervisor who mainly cares about what methods you use and why.
  
Therefore, although final performance of the model is important, it is also necessary to explain your approach and justify your choices.

The problem can be broken down into the following tasks:
- A) Data exploration and pre-processing
- B) Model building
- C) Training and validation
- D) Evaluation of the performance on test data

All of your answers should be written in this notebook, which should be able to run without error.

Use "markdown" cells to include explanations of your work. 

This notebook, along with your saved model should be uploaded to canvas as your submission.

## Data loading
Below, the dataset is loaded as a pandas dataframe. It is up to you to decide how to manipulate this data and how to use it to solve the problem. The 'label' column contains labels for each image. The 'pixel_1', 'pixel_2', etc columns contain the pixel values for the images of the dice. These were originally taken from a 28 x 28 size monochrome image.

In [1]:
import numpy as np
import pandas as pd

# the following code loads the training and validation data
data_df = pd.read_csv('data.csv')
data_df

,label,pixel_0,pixel_1,pixel_2,pixel_3,pixel_4,pixel_5,pixel_6,pixel_7,pixel_8,...,pixel_774,pixel_775,pixel_776,pixel_777,pixel_778,pixel_779,pixel_780,pixel_781,pixel_782,pixel_783
0,5,110,107,103,100,97,94,90,87,84,...,29,26,22,19,16,13,9,6,3,0
1,5,10,10,10,9,9,8,8,8,7,...,111,100,86,81,78,77,76,75,75,75
2,1,0,0,1,1,2,3,3,4,5,...,61,62,63,63,64,65,65,66,67,67
3,1,10,11,12,13,14,15,15,16,17,...,17,16,17,18,19,20,21,22,23,23
4,6,29,28,27,25,24,23,22,21,20,...,19,18,17,16,15,14,12,11,10,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,4,0,0,0,1,1,2,2,2,3,...,53,53,54,54,55,55,55,56,56,57
380,3,15,15,14,14,13,12,12,11,11,...,56,55,55,54,54,53,52,52,51,51
381,3,20,19,18,18,17,16,15,15,14,...,40,40,39,38,37,36,36,35,34,33
382,2,40,41,42,42,43,44,45,45,46,...,13,13,14,15,16,16,17,18,19,19
383,5,101,98,96,93,91,88,85,83,80,...,23,21,18,15,13,10,7,5,2,0

# Task A: Data exploration, model selection and data pre-processing
In this part you should:
- a) Describe the shape of the dataset
- b) Examine the image data and describe qualitatively
- c) Determine indexes for the classification task
- d) Describe how you are going to proceed, what type of model you are going to use and why
- e) Perform any splitting and pre-processing on the data that you need for your approach

# Task B: Model building
In this part you should build a pytorch model for the classification task. This should include
- a) The code defining the class for the model
- b) An explanation of the architecture of the class (using comments in the code)
- c) A demonstration that the model is structurally correct - i.e. that the forward method is suitable
- d) Calculate of the accuracy of the untrained model and describe if it is consistent with expectations

# Task C: Model training and Validation
In this part you should train your pytorch model. As you perform this task you may refine your model class to improve perfomance. Please comment on this process for the final task of this part. This part should include:
- a) Defining functions for training and validating your model on the data
- b) Appropriate choice of loss function for the task
- c) An explanation of the logic of the training and validation code 
- d) Outputs from your code to show the training and validation loss and accuracy during multiple training epochs
- e) Comments on the training performance of your model - including any modifications made to the model and/or data to improve the performance

# Task D: Model deployment, testing and performance evaluation
In this part you should test your model on the test data provided below. You should:
- a) Obtain the predicted labels from your model and determine its accuracy
- b) Describe the performance and compare both to the training and validation data
- c) Is the training and validation data representative of the test data?
- d) What are the factors limiting model performance and how might the performance be improved
- e) Describe the complexity of your model and how long it takes to make predictions on the test data
- f) Save your fully trained model weights to file

In [2]:
# the following code loads the test data
test_df = pd.read_csv('test.csv')
test_df.head()

,label,pixel_0,pixel_1,pixel_2,pixel_3,pixel_4,pixel_5,pixel_6,pixel_7,pixel_8,...,pixel_774,pixel_775,pixel_776,pixel_777,pixel_778,pixel_779,pixel_780,pixel_781,pixel_782,pixel_783
0,4,0,1,2,3,4,5,6,7,8,...,87,88,89,90,91,92,93,94,96,97
1,3,255,255,254,254,253,252,252,251,251,...,225,225,224,223,223,222,222,221,220,220
2,3,3,5,6,8,9,11,12,14,15,...,26,28,29,31,32,34,35,37,38,40
3,3,0,0,1,1,2,2,3,3,4,...,73,73,74,74,75,75,76,76,77,77
4,5,22,22,22,21,21,21,20,20,19,...,3,3,2,2,1,1,1,0,0,0

## Appendix: Python environment
Standard environment:
- torch                      2.6.0
- torchvision                0.21.0
- transformers               4.52.1
- tokenizers                 0.21.1
- sentencepiece              0.2.0
- scikit-learn               1.6.1
- scipy                      1.15.2
- pandas                     2.2.3
- numpy                      2.2.6
- matplotlib                 3.10.3

List any additional packages imported or if you have used different versions (only include packages you import or import from, not also their dependencies) Also, you should briefly explain any differences (e.g. compatibility with your hardware, or additional package used to provide some extra capabilities.)